---
title: "Day 14: Leaflet + Quarto"
author: "John Zobitz"
format:
  html:
    embed-resources: true
editor: source
server: shiny
---

# Preliminaries

Here is a mashup of code to produce the three digit zip code plots.
```{r}
#| context: setup
#| echo: false
#| message: false

library(tidyverse)
library(sf)     # R wrapper around GDAL/OGR
library(leaflet)    # for fortifying shapefiles
library(shiny)

zips <- st_read(dsn = "Zip_Codes/", layer = "Zip_Codes")


# Create your own listing of zip codes
unique_zips <- zips$NAME_TXT |> unique()

# Define a function for the different colors in each zip
zip_pal <-colorFactor(palette = "RdYlBu",
                      domain = zips$NAME_TXT
)

three_digit_zips <- tibble( zips_all = unique_zips,
                            three_digit_zip = str_extract(unique_zips,pattern="^.{3}") )


# now join
zips2 <- zips |>
  inner_join(three_digit_zips,by=c("NAME_TXT"="zips_all"))


### now let's roll up!
zips3 <- zips2 |>
  st_make_valid() |>
  group_by(three_digit_zip) |>
  summarize()

# Define a function for the different colors in each five digit zip
zip_pal <-colorFactor(palette = "RdYlBu",
                      domain = unique_zips
)

# Define a function for the different colors in each three digit zip
zip3_pal <-colorFactor(palette = "RdYlBu",
                      domain = three_digit_zips$three_digit_zip
)
```



```{r}
#| context: server

# Reproject the zips data frame
zips_reproj <- zips |>
  st_transform('+proj=longlat +datum=WGS84')

zips3_reproj <- zips3 |>
  st_transform('+proj=longlat +datum=WGS84')

# Create the map
map <- leaflet() |> 
  addTiles() |> 
  addPolygons(data = zips_reproj,
              weight = 1,
              color = "white",
              fillColor = ~zip_pal(NAME_TXT),
              fillOpacity = 0.3,
              popup = ~NAME_TXT,
              group = "Five digit zips") |>
    addPolygons(data = zips3_reproj,
                weight = 1,
              color = "red",
              fillColor = ~zip3_pal(three_digit_zip),
              fillOpacity = 0.3,
              popup = ~three_digit_zip,
              group = "Three digit zips") |>
  addLayersControl(
    overlayGroups = c("Five digit zips", "Three digit zips"),
    options = layersControlOptions(collapsed = FALSE)
  )


output$plot <- renderLeaflet({
  map 
  })

```

```{r}
#| panel: fill
leafletOutput('plot')
```
